use_frameworks!

target 'NewsAPISwift_Example' do
  pod 'NewsAPISwift', :path => '../'

  target 'NewsAPISwift_Tests' do
    inherit! :search_paths
  end

  target 'NewsAPISwift_ExampleTests' do
    inherit! :search_paths
  end
  
end
